# File version: 2.1; date: 2026-05-12

$pdf_mode = 4;
$lualatex = 'lualatex -interaction=nonstopmode -file-line-error %O %S';
$bibtex_use = 2;
$biber = 'biber %O %B';
$makeindex = 'makeindex %O -o %D %S';
$clean_ext = 'aux bbl bcf blg idx ilg ind log out run.xml toc lof lot fls fdb_latexmk synctex.gz nav snm vrb xdv';
$clean_full_ext = 'pdf';
